# ===============================================
#   SFTP Configuration
# ===============================================
sftp.host=sftpusecase.blob.core.windows.net
sftp.username=sftpusecase.upendrathunuguntla
sftp.outbound.path=/retail/outbound


# ===============================================
#   API Manager Details
# ===============================================
api.id=20415175