# ===============================================
#   SendGrid Configuration
# ===============================================
sendgrid.host=api.sendgrid.com

# ===============================================
#   API Manager Details
# ===============================================
api.id=