# ===============================================
#   SFTP Configuration
# ===============================================
sftp.password=![qtnbOJQ8+MU01KPjQuPtrXyysdNX14QfONMnAxlDmv8F58HnM0yKPAXgVIN0WPd8]