# ===============================================
#   SendGrid Configuration
# ===============================================
sendgrid.token=![zlPzHjmiN59NCBek/8d8i/kODS/Es8f4nW9i+Wxcz0yz0jAo3J0UVOrGDeQwX2FSZcat//QpPYyD8CC10bmDsfX+t95H/L1NLxO5Cm7uOqw=]